<?php

return function ($conn) {
    // Create all database tables as they exist, without assuming the existence of users.
    $conn->query("CREATE TABLE IF NOT EXISTS `users` (`UserName` varchar(64) DEFAULT NULL, `PasswordSalt` varchar(255) DEFAULT NULL, `PasswordHash` varchar(255) DEFAULT NULL, `DisplayName` varchar(255) DEFAULT NULL, `ID` varchar(64) NOT NULL, `AccountLevel` int(11) NOT NULL DEFAULT 1, PRIMARY KEY (`ID`), UNIQUE KEY `UserName` (`UserName`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Access` (  `User` varchar(64) DEFAULT NULL,  `Token` varchar(64) NOT NULL,  `TokenScope` int(11) NOT NULL DEFAULT 0,  `TokenFlags` int(11) NOT NULL DEFAULT 0,  `Expire` int(11) NOT NULL DEFAULT 0,  `IssuedAt` int(11) NOT NULL DEFAULT 0,  PRIMARY KEY (`Token`),  UNIQUE KEY `User` (`User`,`Token`),  CONSTRAINT `Access_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Alters` (  `User` varchar(64) NOT NULL,  `ID` varchar(64) NOT NULL,  `Name` varchar(255) DEFAULT NULL,  `Avatar` varchar(64) DEFAULT NULL,  `Fields` blob DEFAULT NULL,  `SubID` int(11) DEFAULT NULL,  `ParentID` varchar(64) DEFAULT NULL,  `Flags` int(11) NOT NULL DEFAULT 0,  PRIMARY KEY (`ID`),  UNIQUE KEY `ID` (`ID`),  KEY `User` (`User`),  CONSTRAINT `Alters_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Audit` (  `ID` varchar(64) NOT NULL,  `RequestType` varchar(12) DEFAULT NULL,  `RequestPath` varchar(255) DEFAULT NULL,  `RequestData` text DEFAULT NULL,  `RequestHeaders` text CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL, `Timestamp` int(11) NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Avatars` (  `User` varchar(64) NOT NULL,  `AlterId` varchar(64) NOT NULL,  `ImageType` varchar(255) NOT NULL DEFAULT 'image/webp',  `ImageBinary` longblob NOT NULL,  `Timestamp` int(11) NOT NULL,  PRIMARY KEY (`AlterId`),  UNIQUE KEY `AlterId` (`AlterId`),  KEY `User` (`User`),  CONSTRAINT `Avatars_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,  CONSTRAINT `Avatars_ibfk_2` FOREIGN KEY (`AlterId`) REFERENCES `Alters` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Feedback` (  `User` varchar(64) NOT NULL,  `ID` varchar(64) NOT NULL,  `Name` varchar(255) NOT NULL,  `Type` int(11) NOT NULL,  `Status` int(11) NOT NULL DEFAULT 0,  `RootMessage` varchar(64) DEFAULT NULL,  `LastMessage` varchar(64) DEFAULT NULL,  `Created` int(11) NOT NULL,  `Updated` int(11) NOT NULL,  PRIMARY KEY (`ID`),  UNIQUE KEY `ID` (`ID`),  KEY `User` (`User`),  CONSTRAINT `Feedback_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `FeedbackMessages` (  `ID` varchar(64) NOT NULL,  `Feedback` varchar(64) NOT NULL,  `User` varchar(64) NOT NULL,  `Message` text NOT NULL,  `Created` int(11) NOT NULL,  PRIMARY KEY (`ID`),  UNIQUE KEY `ID` (`ID`),  KEY `User` (`User`),  KEY `Feedback` (`Feedback`),  CONSTRAINT `FeedbackMessages_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,  CONSTRAINT `FeedbackMessages_ibfk_2` FOREIGN KEY (`Feedback`) REFERENCES `Feedback` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Fields` (  `User` varchar(64) NOT NULL,  `ID` varchar(64) NOT NULL,  `FieldName` varchar(255) NOT NULL,  `FieldType` int(11) NOT NULL DEFAULT 1,  `SortOrder` int(11) NOT NULL DEFAULT 0,  PRIMARY KEY (`ID`),  UNIQUE KEY `User` (`User`,`ID`),  CONSTRAINT `Fields_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Fronting` ( `ID` varchar(64) NOT NULL,  `User` varchar(64) NOT NULL,  `AlterID` varchar(64) NOT NULL,  `StartTime` int(11) NOT NULL DEFAULT 0,  `EndTime` int(11) NOT NULL DEFAULT 0,  PRIMARY KEY (`ID`),  UNIQUE KEY `ID` (`ID`),  KEY `User` (`User`),  KEY `AlterID` (`AlterID`),  CONSTRAINT `Fronting_ibfk_1` FOREIGN KEY (`User`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `Fronting_ibfk_2` FOREIGN KEY (`AlterID`) REFERENCES `Alters` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");

    $conn->query("CREATE TABLE IF NOT EXISTS `Images` (  `OwnerID` varchar(64) NOT NULL,  `ImageID` varchar(64) NOT NULL,  `ImageType` varchar(255) NOT NULL DEFAULT 'image/webp',  `ImageBinary` longblob NOT NULL,  `Timestamp` int(11) NOT NULL,  PRIMARY KEY (`ImageID`),  UNIQUE KEY `ImageID` (`ImageID`),  KEY `OwnerID` (`OwnerID`),  CONSTRAINT `Images_ibfk_1` FOREIGN KEY (`OwnerID`) REFERENCES `users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;");
}

?>